### ISSUE TITLE
Biome Music does not stop when playing a music disc

### ISSUE THREAD

**Issue by DelirusCrux** [jss2a98aj/Et-Futurum#1] opened 2021-01-27 02:45 UTC
See title yo

**Comment by Roadhog360** [comment] 2021-01-27 09:09
I checked this, and it's a bug in vanilla. If BugTorch fixes it I'll make sure the fix works with my music too.

For now I'll be closing this under "Works as Intended" since vanilla music is not stopped.

Video:
https://streamable.com/id9y6r

**Closed** 2021-01-27 09:09 UTC
Labels: Bug, Priority: Normal
