### ISSUE TITLE
Disabling anything will cause a crash.

### ISSUE THREAD

**Issue by MagmaBro123** [jss2a98aj/Et-Futurum#23] opened 2021-04-02 02:51 UTC
[crash-2021-04-01_20.49.48-client.txt](https://github.com/jss2a98aj/Et-Futurum/files/6247415/crash-2021-04-01_20.49.48-client.txt)
Read #20 for mod & Forge version.

**Comment by Roadhog360** [comment] 2021-04-02 07:11
What did you disable?

**Comment by MagmaBro123** [comment] 2021-04-02 15:22
Deepslate. Also tried other features. Same issue.

**Comment by Roadhog360** [comment] 2021-04-02 19:24
What is "other" features?

**Comment by MagmaBro123** [comment] 2021-04-02 19:33
Any features that can be toggled via the config.

Husks, endermites, banners, etc.

**Comment by Roadhog360** [comment] 2021-04-02 19:34
But what did you try? I recently tested ome config options on my end and they worked fine so it's not all of tjem

**Comment by Roadhog360** [comment] 2021-04-03 04:57
I tried those three things and smokers, blast furnace, and a few more entities and was not able to find a crash. Closing this as "cannot reproduce" until more information is provided.

**Closed by Roadhog360** 2021-04-03 04:57 UTC
Labels: Bug, Question

**Comment by Roadhog360** [comment] 2021-04-03 17:12
I forgot to mention but the crash report seems to be crashing at the configuration screen. As well as providing exactly what you disabled, what happens if you try disabling the same features with no mods but Et Futurum Requiem? I'll attempt to use the information from the mentioned and this to help fix the issue, will reopen if I can replicate the crash on my end.

**Comment by MagmaBro123** [comment] 2021-04-04 01:14
Sorry for the late response. Apparently 2.1.1 somehow isn’t crashing...

**Comment by Roadhog360** [comment] 2021-04-04 01:15
Perhaps somehow the fix crossed up with this issue by mistake. 2.0.0 was a horrendously broken release.

**Comment by MagmaBro123** [comment] 2021-04-04 20:58
Ah. Didn't know.
